Very preliminary implementation of splitPlotRoc [skip ci]
However, it breaks ROI datatype and causes test failures in devtools::test()

Test failures ─────────────────────────────────────────────────────────────────────────────────────────────── testthat ────

> library("testthat")
> library("RJafroc")
>
> test_check("RJafroc")
── 1. Failure: DfReadDataFile, non_JAFROC, see below (@test-data-file.R#257)  ────────────────────────────────────────────────
DfReadDataFile(fileName, format = "MRMC") not equal to `ds`.
Names: 1 string mismatch

── 2. Failure: DfReadDataFile, non_JAFROC, see below (@test-data-file.R#271)  ────────────────────────────────────────────────
DfReadDataFile(fileName, format = "iMRMC") not equal to `ds`.
Names: 1 string mismatch

── 3. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#303)  ────────────────────────────────────────
DfReadDataFile(fileName) not equal to `ds`.
Names: 1 string mismatch

── 4. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#317)  ────────────────────────────────────────
DfReadDataFile(fileName) not equal to `ds`.
Names: 1 string mismatch

── 5. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#332)  ────────────────────────────────────────
DfReadDataFile(fileName, renumber = TRUE) not equal to `ds`.
Names: 1 string mismatch

── 6. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#346)  ────────────────────────────────────────
DfReadDataFile(fileName) not equal to `ds`.
Names: 1 string mismatch
Component "dataType": 1 string mismatch

── 7. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#350)  ────────────────────────────────────────
ds$dataType not equal to "ROI".
1/1 mismatches
x[1]: "FROC"
y[1]: "ROI"

══ testthat results  ═════════════════════════════════════════════════════════════════════════════════════════════════════════
[ OK: 139 | SKIPPED: 7 | WARNINGS: 0 | FAILED: 7 ]
1. Failure: DfReadDataFile, non_JAFROC, see below (@test-data-file.R#257)
2. Failure: DfReadDataFile, non_JAFROC, see below (@test-data-file.R#271)
3. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#303)
4. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#317)
5. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#332)
6. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#346)
7. Failure: DfReadDataFile, JAFROC: it does ALL paradigms (@test-data-file.R#350)

Error: testthat unit tests failed
Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔