CRAN submission process 1 of xx
System Software Overview:

  System Version:	macOS 10.15.7 (19H1922)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Dev’s iMac
  User Name:	Dev Chakraborty (Dev)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	24 days 8 minutes

macOS Catalina
10.15.7 (19H1922)

cran4  branch
deleted all but 2 SS vignettes

r cmd check
checking installed package size ... NOTE
    installed size is  5.1Mb
    sub-directories of 1Mb or more:
      doc       1.6Mb
      extdata   1.7Mb

deleted all files in doc

r cmd check
same as above

updated R to 4.2.1
Had to reinstall many packages
r cmd check
Files in the 'vignettes' directory but no files in 'inst/doc':

moved doc to inst
Install and restart
Error: package or namespace load failed for ‘RJafroc’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RJafroc/libs/RJafroc.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RJafroc/libs/RJafroc.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RJafroc/libs/RJafroc.so
  Reason: image not found
Clean and rebuild fixes above error

r cmd check
checking installed package size ... NOTE
    installed size is  5.1Mb
    sub-directories of 1Mb or more:
      doc       1.6Mb
      extdata   1.7Mb

## TEMP CRAN submission process
* Version 2.0.1
* This is on `cran3` branch.
* Steps to reduce file size to less than 5 Mb:
    + Removed `tests` and `vignettes` (this needs to be done on all computers I am using).
    + Removed all files from `inst/MRMCRuns` except `Tony`, the one that is used in an example.
    + Removed `CrossedModalities.xlsx` and references to it.
    + Removed `DfReadLrocDataFile.R` and `findings.txt`. Ran `devtools::document()` to fix `NAMESPACE`.
    + Removed `RoiData.xlsx`.
* Otherwise identical to `developer` and `master` as of 12/8/20.
* `testthat` failure on Ubuntu developer is resolved, see `master` branch: `checkEnvironment = FALSE` in `expect_equal()` on `ggplot2` comparisons to `goodValues`.
* On CRAN

deleted RoiData.xlsx
── R CMD check results ─────────────────────────── RJafroc 2.0.1.9000 ────
Duration: 4m 43s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded